CREATE TABLE `nation` (
`country_code` varchar(2) NOT NULL default '',
`country_enName` varchar(100) NOT NULL default '',
`country_arName` varchar(100) NOT NULL default '',
`country_enNationality` varchar(100) NOT NULL default '',
`country_arNationality` varchar(100) NOT NULL default '',
PRIMARY KEY (`country_code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
-- 
-- Dumping data for table `nation`
-- 
INSERT INTO `nation` VALUES ('AF', 'Afghanistan','أفغانستان','Afghan','أفغانستاني');
INSERT INTO `nation` VALUES ('AL', 'Albania','ألبانيا','Albanian','ألباني');
INSERT INTO `nation` VALUES ('AX', 'Aland Islands','جزر آلاند','Aland Islander','آلاندي');
INSERT INTO `nation` VALUES ('DZ', 'Algeria','الجزائر','Algerian','جزائري');
INSERT INTO `nation` VALUES ('AS', 'American Samoa','ساموا-الأمريكي','American Samoan','أمريكي سامواني');
INSERT INTO `nation` VALUES ('AD', 'Andorra','أندورا','Andorran','أندوري');
INSERT INTO `nation` VALUES ('AO', 'Angola','أنغولا','Angolan','أنقولي');
INSERT INTO `nation` VALUES ('AI', 'Anguilla','أنغويلا','Anguillan','أنغويلي');
INSERT INTO `nation` VALUES ('AQ', 'Antarctica','أنتاركتيكا','Antarctican','أنتاركتيكي');
INSERT INTO `nation` VALUES ('AG', 'Antigua and Barbuda','أنتيغوا وبربودا','Antiguan','بربودي');
INSERT INTO `nation` VALUES ('AR', 'Argentina','الأرجنتين','Argentinian','أرجنتيني');
INSERT INTO `nation` VALUES ('AM', 'Armenia','أرمينيا','Armenian','أرميني');
INSERT INTO `nation` VALUES ('AW', 'Aruba','أروبه','Aruban','أوروبهيني');
INSERT INTO `nation` VALUES ('AU', 'Australia','أستراليا','Australian','أسترالي');
INSERT INTO `nation` VALUES ('AT', 'Austria','النمسا','Austrian','نمساوي');
INSERT INTO `nation` VALUES ('AZ', 'Azerbaijan','أذربيجان','Azerbaijani','أذربيجاني');
INSERT INTO `nation` VALUES ('BS', 'Bahamas','الباهاماس','Bahamian','باهاميسي');
INSERT INTO `nation` VALUES ('BH', 'Bahrain','البحرين','Bahraini','بحريني');
INSERT INTO `nation` VALUES ('BD', 'Bangladesh','بنغلاديش','Bangladeshi','بنغلاديشي');
INSERT INTO `nation` VALUES ('BB', 'Barbados','بربادوس','Barbadian','بربادوسي');
INSERT INTO `nation` VALUES ('BY', 'Belarus','روسيا البيضاء','Belarusian','روسي');
INSERT INTO `nation` VALUES ('BE', 'Belgium','بلجيكا','Belgian','بلجيكي');
INSERT INTO `nation` VALUES ('BZ', 'Belize','بيليز','Belizean','بيليزي');
INSERT INTO `nation` VALUES ('BJ', 'Benin','بنين','Beninese','بنيني');
INSERT INTO `nation` VALUES ('BL', 'Saint Barthelemy','سان بارتيلمي','Saint Barthelmian','سان بارتيلمي');
INSERT INTO `nation` VALUES ('BM', 'Bermuda','جزر برمودا','Bermudan','برمودي');
INSERT INTO `nation` VALUES ('BT', 'Bhutan','بوتان','Bhutanese','بوتاني');
INSERT INTO `nation` VALUES ('BO', 'Bolivia','بوليفيا','Bolivian','بوليفي');
INSERT INTO `nation` VALUES ('BA', 'Bosnia and Herzegovina','البوسنة و الهرسك','Bosnian / Herzegovinian','بوسني/هرسكي');
INSERT INTO `nation` VALUES ('BW', 'Botswana','بوتسوانا','Botswanan','بوتسواني');
INSERT INTO `nation` VALUES ('BV', 'Bouvet Island','جزيرة بوفيه','Bouvetian','بوفيهي');
INSERT INTO `nation` VALUES ('BR', 'Brazil','البرازيل','Brazilian','برازيلي');
INSERT INTO `nation` VALUES ('IO', 'British Indian Ocean Territory','إقليم المحيط الهندي البريطاني','British Indian Ocean Territory','إقليم المحيط الهندي البريطاني');
INSERT INTO `nation` VALUES ('BN', 'Brunei Darussalam','بروني','Bruneian','بروني');
INSERT INTO `nation` VALUES ('BG', 'Bulgaria','بلغاريا','Bulgarian','بلغاري');
INSERT INTO `nation` VALUES ('BF', 'Burkina Faso','بوركينا فاسو','Burkinabe','بوركيني');
INSERT INTO `nation` VALUES ('BI', 'Burundi','بوروندي','Burundian','بورونيدي');
INSERT INTO `nation` VALUES ('KH', 'Cambodia','كمبوديا','Cambodian','كمبودي');
INSERT INTO `nation` VALUES ('CM', 'Cameroon','كاميرون','Cameroonian','كاميروني');
INSERT INTO `nation` VALUES ('CA', 'Canada','كندا','Canadian','كندي');
INSERT INTO `nation` VALUES ('CV', 'Cape Verde','الرأس الأخضر','Cape Verdean','الرأس الأخضر');
INSERT INTO `nation` VALUES ('KY', 'Cayman Islands','جزر كايمان','Caymanian','كايماني');
INSERT INTO `nation` VALUES ('CF', 'Central African Republic','جمهورية أفريقيا الوسطى','Central African','أفريقي');
INSERT INTO `nation` VALUES ('TD', 'Chad','تشاد','Chadian','تشادي');
INSERT INTO `nation` VALUES ('CL', 'Chile','شيلي','Chilean','شيلي');
INSERT INTO `nation` VALUES ('CN', 'China','الصين','Chinese','صيني');
INSERT INTO `nation` VALUES ('CX', 'Christmas Island','جزيرة عيد الميلاد','Christmas Islander','جزيرة عيد الميلاد');
INSERT INTO `nation` VALUES ('CC', 'Cocos (Keeling) Islands','جزر كوكوس','Cocos Islander','جزر كوكوس');
INSERT INTO `nation` VALUES ('CO', 'Colombia','كولومبيا','Colombian','كولومبي');
INSERT INTO `nation` VALUES ('KM', 'Comoros','جزر القمر','Comorian','جزر القمر');
INSERT INTO `nation` VALUES ('CG', 'Congo','الكونغو','Congolese','كونغي');
INSERT INTO `nation` VALUES ('CK', 'Cook Islands','جزر كوك','Cook Islander','جزر كوك');
INSERT INTO `nation` VALUES ('CR', 'Costa Rica','كوستاريكا','Costa Rican','كوستاريكي');
INSERT INTO `nation` VALUES ('HR', 'Croatia','كرواتيا','Croatian','كوراتي');
INSERT INTO `nation` VALUES ('CU', 'Cuba','كوبا','Cuban','كوبي');
INSERT INTO `nation` VALUES ('CY', 'Cyprus','قبرص','Cypriot','قبرصي');
INSERT INTO `nation` VALUES ('CW', 'Curaçao','كوراساو','Curacian','كوراساوي');
INSERT INTO `nation` VALUES ('CZ', 'Czech Republic','الجمهورية التشيكية','Czech','تشيكي');
INSERT INTO `nation` VALUES ('DK', 'Denmark','الدانمارك','Danish','دنماركي');
INSERT INTO `nation` VALUES ('DJ', 'Djibouti','جيبوتي','Djiboutian','جيبوتي');
INSERT INTO `nation` VALUES ('DM', 'Dominica','دومينيكا','Dominican','دومينيكي');
INSERT INTO `nation` VALUES ('DO', 'Dominican Republic','الجمهورية الدومينيكية','Dominican','دومينيكي');
INSERT INTO `nation` VALUES ('EC', 'Ecuador','إكوادور','Ecuadorian','إكوادوري');
INSERT INTO `nation` VALUES ('EG', 'Egypt','مصر','Egyptian','مصري');
INSERT INTO `nation` VALUES ('SV', 'El Salvador','إلسلفادور','Salvadoran','سلفادوري');
INSERT INTO `nation` VALUES ('GQ', 'Equatorial Guinea','غينيا الاستوائي','Equatorial Guinean','غيني');
INSERT INTO `nation` VALUES ('ER', 'Eritrea','إريتريا','Eritrean','إريتيري');
INSERT INTO `nation` VALUES ('EE', 'Estonia','استونيا','Estonian','استوني');
INSERT INTO `nation` VALUES ('ET', 'Ethiopia','أثيوبيا','Ethiopian','أثيوبي');
INSERT INTO `nation` VALUES ('FK', 'Falkland Islands (Malvinas)','جزر فوكلاند','Falkland Islander','فوكلاندي');
INSERT INTO `nation` VALUES ('FO', 'Faroe Islands','جزر فارو','Faroese','جزر فارو');
INSERT INTO `nation` VALUES ('FJ', 'Fiji','فيجي','Fijian','فيجي');
INSERT INTO `nation` VALUES ('FI', 'Finland','فنلندا','Finnish','فنلندي');
INSERT INTO `nation` VALUES ('FR', 'France','فرنسا','French','فرنسي');
INSERT INTO `nation` VALUES ('GF', 'French Guiana','غويانا الفرنسية','French Guianese','غويانا الفرنسية');
INSERT INTO `nation` VALUES ('PF', 'French Polynesia','بولينيزيا الفرنسية','French Polynesian','بولينيزيي');
INSERT INTO `nation` VALUES ('TF', 'French Southern and Antarctic Lands','أراض فرنسية جنوبية وأنتارتيكية','French','أراض فرنسية جنوبية وأنتارتيكية');
INSERT INTO `nation` VALUES ('GA', 'Gabon','الغابون','Gabonese','غابوني');
INSERT INTO `nation` VALUES ('GM', 'Gambia','غامبيا','Gambian','غامبي');
INSERT INTO `nation` VALUES ('GE', 'Georgia','جيورجيا','Georgian','جيورجي');
INSERT INTO `nation` VALUES ('DE', 'Germany','ألمانيا','German','ألماني');
INSERT INTO `nation` VALUES ('GH', 'Ghana','غانا','Ghanaian','غاني');
INSERT INTO `nation` VALUES ('GI', 'Gibraltar','جبل طارق','Gibraltar','جبل طارق');
INSERT INTO `nation` VALUES ('GG', 'Guernsey','غيرنزي','Guernsian','غيرنزي');
INSERT INTO `nation` VALUES ('GR', 'Greece','اليونان','Greek','يوناني');
INSERT INTO `nation` VALUES ('GL', 'Greenland','جرينلاند','Greenlandic','جرينلاندي');
INSERT INTO `nation` VALUES ('GD', 'Grenada','غرينادا','Grenadian','غرينادي');
INSERT INTO `nation` VALUES ('GP', 'Guadeloupe','جزر جوادلوب','Guadeloupe','جزر جوادلوب');
INSERT INTO `nation` VALUES ('GU', 'Guam','جوام','Guamanian','جوامي');
INSERT INTO `nation` VALUES ('GT', 'Guatemala','غواتيمال','Guatemalan','غواتيمالي');
INSERT INTO `nation` VALUES ('GN', 'Guinea','غينيا','Guinean','غيني');
INSERT INTO `nation` VALUES ('GW', 'Guinea-Bissau','غينيا-بيساو','Guinea-Bissauan','غيني');
INSERT INTO `nation` VALUES ('GY', 'Guyana','غيانا','Guyanese','غياني');
INSERT INTO `nation` VALUES ('HT', 'Haiti','هايتي','Haitian','هايتي');
INSERT INTO `nation` VALUES ('HM', 'Heard and Mc Donald Islands','جزيرة هيرد وجزر ماكدونالد','Heard and Mc Donald Islanders','جزيرة هيرد وجزر ماكدونالد');
INSERT INTO `nation` VALUES ('HN', 'Honduras','هندوراس','Honduran','هندوراسي');
INSERT INTO `nation` VALUES ('HK', 'Hong Kong','هونغ كونغ','Hongkongese','هونغ كونغي');
INSERT INTO `nation` VALUES ('HU', 'Hungary','المجر','Hungarian','مجري');
INSERT INTO `nation` VALUES ('IS', 'Iceland','آيسلندا','Icelandic','آيسلندي');
INSERT INTO `nation` VALUES ('IN', 'India','الهند','Indian','هندي');
INSERT INTO `nation` VALUES ('IM', 'Isle of Man','جزيرة مان','Manx','ماني');
INSERT INTO `nation` VALUES ('ID', 'Indonesia','أندونيسيا','Indonesian','أندونيسيي');
INSERT INTO `nation` VALUES ('IR', 'Iran','إيران','Iranian','إيراني');
INSERT INTO `nation` VALUES ('IQ', 'Iraq','العراق','Iraqi','عراقي');
INSERT INTO `nation` VALUES ('IE', 'Ireland','إيرلندا','Irish','إيرلندي');
INSERT INTO `nation` VALUES ('IL', 'Israel','إسرائيل','Israeli','إسرائيلي');
INSERT INTO `nation` VALUES ('IT', 'Italy','إيطاليا','Italian','إيطالي');
INSERT INTO `nation` VALUES ('CI', 'Ivory Coast','ساحل العاج','Ivory Coastian','ساحل العاج');
INSERT INTO `nation` VALUES ('JE', 'Jersey','جيرزي','Jersian','جيرزي');
INSERT INTO `nation` VALUES ('JM', 'Jamaica','جمايكا','Jamaican','جمايكي');
INSERT INTO `nation` VALUES ('JP', 'Japan','اليابان','Japanese','ياباني');
INSERT INTO `nation` VALUES ('JO', 'Jordan','الأردن','Jordanian','أردني');
INSERT INTO `nation` VALUES ('KZ', 'Kazakhstan','كازاخستان','Kazakh','كازاخستاني');
INSERT INTO `nation` VALUES ('KE', 'Kenya','كينيا','Kenyan','كيني');
INSERT INTO `nation` VALUES ('KI', 'Kiribati','كيريباتي','I-Kiribati','كيريباتي');
INSERT INTO `nation` VALUES ('KP', 'Korea(North Korea)','كوريا الشمالية','North Korean','كوري');
INSERT INTO `nation` VALUES ('KR', 'Korea(South Korea)','كوريا الجنوبية','South Korean','كوري');
INSERT INTO `nation` VALUES ('XK', 'Kosovo','كوسوفو','Kosovar','كوسيفي');
INSERT INTO `nation` VALUES ('KW', 'Kuwait','الكويت','Kuwaiti','كويتي');
INSERT INTO `nation` VALUES ('KG', 'Kyrgyzstan','قيرغيزستان','Kyrgyzstani','قيرغيزستاني');
INSERT INTO `nation` VALUES ('LA', 'Lao PDR','لاوس','Laotian','لاوسي');
INSERT INTO `nation` VALUES ('LV', 'Latvia','لاتفيا','Latvian','لاتيفي');
INSERT INTO `nation` VALUES ('LB', 'Lebanon','لبنان','Lebanese','لبناني');
INSERT INTO `nation` VALUES ('LS', 'Lesotho','ليسوتو','Basotho','ليوسيتي');
INSERT INTO `nation` VALUES ('LR', 'Liberia','ليبيريا','Liberian','ليبيري');
INSERT INTO `nation` VALUES ('LY', 'Libya','ليبيا','Libyan','ليبي');
INSERT INTO `nation` VALUES ('LI', 'Liechtenstein','ليختنشتين','Liechtenstein','ليختنشتيني');
INSERT INTO `nation` VALUES ('LT', 'Lithuania','لتوانيا','Lithuanian','لتوانيي');
INSERT INTO `nation` VALUES ('LU', 'Luxembourg','لوكسمبورغ','Luxembourger','لوكسمبورغي');
INSERT INTO `nation` VALUES ('LK', 'Sri Lanka','سريلانكا','Sri Lankian','سريلانكي');
INSERT INTO `nation` VALUES ('MO', 'Macau','ماكاو','Macanese','ماكاوي');
INSERT INTO `nation` VALUES ('MK', 'Macedonia','مقدونيا','Macedonian','مقدوني');
INSERT INTO `nation` VALUES ('MG', 'Madagascar','مدغشقر','Malagasy','مدغشقري');
INSERT INTO `nation` VALUES ('MW', 'Malawi','مالاوي','Malawian','مالاوي');
INSERT INTO `nation` VALUES ('MY', 'Malaysia','ماليزيا','Malaysian','ماليزي');
INSERT INTO `nation` VALUES ('MV', 'Maldives','المالديف','Maldivian','مالديفي');
INSERT INTO `nation` VALUES ('ML', 'Mali','مالي','Malian','مالي');
INSERT INTO `nation` VALUES ('MT', 'Malta','مالطا','Maltese','مالطي');
INSERT INTO `nation` VALUES ('MH', 'Marshall Islands','جزر مارشال','Marshallese','مارشالي');
INSERT INTO `nation` VALUES ('MQ', 'Martinique','مارتينيك','Martiniquais','مارتينيكي');
INSERT INTO `nation` VALUES ('MR', 'Mauritania','موريتانيا','Mauritanian','موريتانيي');
INSERT INTO `nation` VALUES ('MU', 'Mauritius','موريشيوس','Mauritian','موريشيوسي');
INSERT INTO `nation` VALUES ('YT', 'Mayotte','مايوت','Mahoran','مايوتي');
INSERT INTO `nation` VALUES ('MX', 'Mexico','المكسيك','Mexican','مكسيكي');
INSERT INTO `nation` VALUES ('FM', 'Micronesia','مايكرونيزيا','Micronesian','مايكرونيزيي');
INSERT INTO `nation` VALUES ('MD', 'Moldova','مولدافيا','Moldovan','مولديفي');
INSERT INTO `nation` VALUES ('MC', 'Monaco','موناكو','Monacan','مونيكي');
INSERT INTO `nation` VALUES ('MN', 'Mongolia','منغوليا','Mongolian','منغولي');
INSERT INTO `nation` VALUES ('ME', 'Montenegro','الجبل الأسود','Montenegrin','الجبل الأسود');
INSERT INTO `nation` VALUES ('MS', 'Montserrat','مونتسيرات','Montserratian','مونتسيراتي');
INSERT INTO `nation` VALUES ('MA', 'Morocco','المغرب','Moroccan','مغربي');
INSERT INTO `nation` VALUES ('MZ', 'Mozambique','موزمبيق','Mozambican','موزمبيقي');
INSERT INTO `nation` VALUES ('MM', 'Myanmar','ميانمار','Myanmarian','ميانماري');
INSERT INTO `nation` VALUES ('NA', 'Namibia','ناميبيا','Namibian','ناميبي');
INSERT INTO `nation` VALUES ('NR', 'Nauru','نورو','Nauruan','نوري');
INSERT INTO `nation` VALUES ('NP', 'Nepal','نيبال','Nepalese','نيبالي');
INSERT INTO `nation` VALUES ('NL', 'Netherlands','هولندا','Dutch','هولندي');
INSERT INTO `nation` VALUES ('AN', 'Netherlands Antilles','جزر الأنتيل الهولندي','Dutch Antilier','هولندي');
INSERT INTO `nation` VALUES ('NC', 'New Caledonia','كاليدونيا الجديدة','New Caledonian','كاليدوني');
INSERT INTO `nation` VALUES ('NZ', 'New Zealand','نيوزيلندا','New Zealander','نيوزيلندي');
INSERT INTO `nation` VALUES ('NI', 'Nicaragua','نيكاراجوا','Nicaraguan','نيكاراجوي');
INSERT INTO `nation` VALUES ('NE', 'Niger','النيجر','Nigerien','نيجيري');
INSERT INTO `nation` VALUES ('NG', 'Nigeria','نيجيريا','Nigerian','نيجيري');
INSERT INTO `nation` VALUES ('NU', 'Niue','ني','Niuean','ني');
INSERT INTO `nation` VALUES ('NF', 'Norfolk Island','جزيرة نورفولك','Norfolk Islander','نورفوليكي');
INSERT INTO `nation` VALUES ('MP', 'Northern Mariana Islands','جزر ماريانا الشمالية','Northern Marianan','ماريني');
INSERT INTO `nation` VALUES ('NO', 'Norway','النرويج','Norwegian','نرويجي');
INSERT INTO `nation` VALUES ('OM', 'Oman','عمان','Omani','عماني');
INSERT INTO `nation` VALUES ('PK', 'Pakistan','باكستان','Pakistani','باكستاني');
INSERT INTO `nation` VALUES ('PW', 'Palau','بالاو','Palauan','بالاوي');
INSERT INTO `nation` VALUES ('PS', 'Palestine','فلسطين','Palestinian','فلسطيني');
INSERT INTO `nation` VALUES ('PA', 'Panama','بنما','Panamanian','بنمي');
INSERT INTO `nation` VALUES ('PG', 'Papua New Guinea','بابوا غينيا الجديدة','Papua New Guinean','بابوي');
INSERT INTO `nation` VALUES ('PY', 'Paraguay','باراغواي','Paraguayan','بارغاوي');
INSERT INTO `nation` VALUES ('PE', 'Peru','بيرو','Peruvian','بيري');
INSERT INTO `nation` VALUES ('PH', 'Philippines','الفليبين','Filipino','فلبيني');
INSERT INTO `nation` VALUES ('PN', 'Pitcairn','بيتكيرن','Pitcairn Islander','بيتكيرني');
INSERT INTO `nation` VALUES ('PL', 'Poland','بولندا','Polish','بولندي');
INSERT INTO `nation` VALUES ('PT', 'Portugal','البرتغال','Portuguese','برتغالي');
INSERT INTO `nation` VALUES ('PR', 'Puerto Rico','بورتو ريكو','Puerto Rican','بورتي');
INSERT INTO `nation` VALUES ('QA', 'Qatar','قطر','Qatari','قطري');
INSERT INTO `nation` VALUES ('RE', 'Reunion Island','ريونيون','Reunionese','ريونيوني');
INSERT INTO `nation` VALUES ('RO', 'Romania','رومانيا','Romanian','روماني');
INSERT INTO `nation` VALUES ('RU', 'Russian','روسيا','Russian','روسي');
INSERT INTO `nation` VALUES ('RW', 'Rwanda','رواندا','Rwandan','رواندا');
INSERT INTO `nation` VALUES ('KN', 'Saint Kitts and Nevis','سانت كيتس ونيفس,','Kittitian/Nevisian','سانت كيتس ونيفس');
INSERT INTO `nation` VALUES ('MF', 'Saint Martin (French part)','ساينت مارتن فرنسي','St. Martian(French)','ساينت مارتني فرنسي');
INSERT INTO `nation` VALUES ('SX', 'Sint Maarten (Dutch part)','ساينت مارتن هولندي','St. Martian(Dutch)','ساينت مارتني هولندي');
INSERT INTO `nation` VALUES ('LC', 'Saint Pierre and Miquelon','سان بيير وميكلون','St. Pierre and Miquelon','سان بيير وميكلوني');
INSERT INTO `nation` VALUES ('VC', 'Saint Vincent and the Grenadines','سانت فنسنت وجزر غرينادين','Saint Vincent and the Grenadines','سانت فنسنت وجزر غرينادين');
INSERT INTO `nation` VALUES ('WS', 'Samoa','ساموا','Samoan','ساموي');
INSERT INTO `nation` VALUES ('SM', 'San Marino','سان مارينو','Sammarinese','ماريني');
INSERT INTO `nation` VALUES ('ST', 'Sao Tome and Principe','ساو تومي وبرينسيبي','Sao Tomean','ساو تومي وبرينسيبي');
INSERT INTO `nation` VALUES ('SA', 'Saudi Arabia','المملكة العربية السعودية','Saudi Arabian','سعودي');
INSERT INTO `nation` VALUES ('SN', 'Senegal','السنغال','Senegalese','سنغالي');
INSERT INTO `nation` VALUES ('RS', 'Serbia','صربيا','Serbian','صربي');
INSERT INTO `nation` VALUES ('SC', 'Seychelles','سيشيل','Seychellois','سيشيلي');
INSERT INTO `nation` VALUES ('SL', 'Sierra Leone','سيراليون','Sierra Leonean','سيراليوني');
INSERT INTO `nation` VALUES ('SG', 'Singapore','سنغافورة','Singaporean','سنغافوري');
INSERT INTO `nation` VALUES ('SK', 'Slovakia','سلوفاكيا','Slovak','سولفاكي');
INSERT INTO `nation` VALUES ('SI', 'Slovenia','سلوفينيا','Slovenian','سولفيني');
INSERT INTO `nation` VALUES ('SB', 'Solomon Islands','جزر سليمان','Solomon Island','جزر سليمان');
INSERT INTO `nation` VALUES ('SO', 'Somalia','الصومال','Somali','صومالي');
INSERT INTO `nation` VALUES ('ZA', 'South Africa','جنوب أفريقيا','South African','أفريقي');
INSERT INTO `nation` VALUES ('GS', 'South Georgia and the South Sandwich','المنطقة القطبية الجنوبية','South Georgia and the South Sandwich','لمنطقة القطبية الجنوبية');
INSERT INTO `nation` VALUES ('SS', 'South Sudan','السودان الجنوبي','South Sudanese','سوادني جنوبي');
INSERT INTO `nation` VALUES ('ES', 'Spain','إسبانيا','Spanish','إسباني');
INSERT INTO `nation` VALUES ('SH', 'Saint Helena','سانت هيلانة','St. Helenian','هيلاني');
INSERT INTO `nation` VALUES ('SD', 'Sudan','السودان','Sudanese','سوداني');
INSERT INTO `nation` VALUES ('SR', 'Suriname','سورينام','Surinamese','سورينامي');
INSERT INTO `nation` VALUES ('SJ', 'Svalbard and Jan Mayen','سفالبارد ويان ماين','Svalbardian/Jan Mayenian','سفالبارد ويان ماين');
INSERT INTO `nation` VALUES ('SZ', 'Swaziland','سوازيلند','Swazi','سوازيلندي');
INSERT INTO `nation` VALUES ('SE', 'Sweden','السويد','Swedish','سويدي');
INSERT INTO `nation` VALUES ('CH', 'Switzerland','سويسرا','Swiss','سويسري');
INSERT INTO `nation` VALUES ('SY', 'Syria','سوريا','Syrian','سوري');
INSERT INTO `nation` VALUES ('TW', 'Taiwan','تايوان','Taiwanese','تايواني');
INSERT INTO `nation` VALUES ('TJ', 'Tajikistan','طاجيكستان','Tajikistani','طاجيكستاني');
INSERT INTO `nation` VALUES ('TZ', 'Tanzania','تنزانيا','Tanzanian','تنزانيي');
INSERT INTO `nation` VALUES ('TH', 'Thailand','تايلندا','Thai','تايلندي');
INSERT INTO `nation` VALUES ('TL', 'Timor-Leste','تيمور الشرقية','Timor-Lestian','تيموري');
INSERT INTO `nation` VALUES ('TG', 'Togo','توغو','Togolese','توغي');
INSERT INTO `nation` VALUES ('TK', 'Tokelau','توكيلاو','Tokelaian','توكيلاوي');
INSERT INTO `nation` VALUES ('TO', 'Tonga','تونغا','Tongan','تونغي');
INSERT INTO `nation` VALUES ('TT', 'Trinidad and Tobago','ترينيداد وتوباغو','Trinidadian/Tobagonian','ترينيداد وتوباغو');
INSERT INTO `nation` VALUES ('TN', 'Tunisia','تونس','Tunisian','تونسي');
INSERT INTO `nation` VALUES ('TR', 'Turkey','تركيا','Turkish','تركي');
INSERT INTO `nation` VALUES ('TM', 'Turkmenistan','تركمانستان','Turkmen','تركمانستاني');
INSERT INTO `nation` VALUES ('TC', 'Turks and Caicos Islands','جزر توركس وكايكوس','Turks and Caicos Islands','جزر توركس وكايكوس');
INSERT INTO `nation` VALUES ('TV', 'Tuvalu','توفالو','Tuvaluan','توفالي');
INSERT INTO `nation` VALUES ('UG', 'Uganda','أوغندا','Ugandan','أوغندي');
INSERT INTO `nation` VALUES ('UA', 'Ukraine','أوكرانيا','Ukrainian','أوكراني');
INSERT INTO `nation` VALUES ('AE', 'United Arab Emirates','الإمارات العربية المتحدة','Emirati','إماراتي');
INSERT INTO `nation` VALUES ('GB', 'United Kingdom','المملكة المتحدة','British','بريطاني');
INSERT INTO `nation` VALUES ('US', 'United States','الولايات المتحدة','American','أمريكي');
INSERT INTO `nation` VALUES ('UM', 'US Minor Outlying Islands','قائمة الولايات والمناطق الأمريكية','US Minor Outlying Islander','أمريكي');
INSERT INTO `nation` VALUES ('UY', 'Uruguay','أورغواي','Uruguayan','أورغواي');
INSERT INTO `nation` VALUES ('UZ', 'Uzbekistan','أوزباكستان','Uzbek','أوزباكستاني');
INSERT INTO `nation` VALUES ('VU', 'Vanuatu','فانواتو','Vanuatuan','فانواتي');
INSERT INTO `nation` VALUES ('VE', 'Venezuela','فنزويلا','Venezuelan','فنزويلي');
INSERT INTO `nation` VALUES ('VN', 'Vietnam','فيتنام','Vietnamese','فيتنامي');
INSERT INTO `nation` VALUES ('VI', 'Virgin Islands (U.S.)','الجزر العذراء الأمريكي','American Virgin Islander','أمريكي');
INSERT INTO `nation` VALUES ('VA', 'Vatican City','فنزويلا','Vatican','فاتيكاني');
INSERT INTO `nation` VALUES ('WF', 'Wallis and Futuna Islands','والس وفوتونا','Wallisian/Futunan','فوتوني');
INSERT INTO `nation` VALUES ('EH', 'Western Sahara','الصحراء الغربية','Sahrawian','صحراوي');
INSERT INTO `nation` VALUES ('YE', 'Yemen','اليمن','Yemeni','يمني');
INSERT INTO `nation` VALUES ('ZM', 'Zambia','زامبيا','Zambian','زامبياني');
INSERT INTO `nation` VALUES ('ZW', 'Zimbabwe','زمبابوي','Zimbabwean','زمبابوي');